### ISSUE TITLE
Dispatcher.Events.Strategies中记录的日志建议过滤UserFriendlyException

### ISSUE THREAD

**Issue by qinxh** [masastack/MASA.Framework#119]
Dispatcher.Events.Strategies中记录的日志建议过滤UserFriendlyException，或者同全局异常处理一样提供自定义的配置

**Comment by doddgu** [comment]
@zhenlei520 PTAL

**Comment by zhenlei520** [comment]
> @zhenlei520 PTAL

I'm looking for time to support

**Comment by zhenlei520** [comment]
This problem has been fixed, if there are no other problems, this pr will be closed after 3 days

**Comment by zhenlei520** [comment]
The problem has been fixed in version 0.5.0, if you still have problems, you can always open the current pr
