### ISSUE TITLE
IMemoryCacheClient不会使用设置好的DB，一直使用DB0

### ISSUE THREAD

**Issue by codding-y** [masastack/MASA.Framework#172]
![image](https://user-images.githubusercontent.com/42963214/182314751-cd73356b-e893-47f6-ac3e-78cd5d05e8a0.png)

**Comment by zhenlei520** [comment]
@codding-y   I'll test it tomorrow

**Comment by zhenlei520** [comment]
问题无法复现，能否提供下demo？
