### ISSUE TITLE
UserContext中Roles使用数组或字典，不使用IdentityRole

### ISSUE THREAD

**Issue by qinxh** [masastack/MASA.Framework#178]
UserContext中Roles使用数组或字典，这样对于使用者集成Masa会更友好。
如果我们直接早已封装好ICurrentUser，不过我们的Roles使用的是数组 `string[] Roles { get; }`
目前升级0.5，为了兼容MASA，底层封装也得同步调整，必须引入Masa.BuildingBlocks.Identity.IdentityModel。
如果UserContext中Roles使用数组或字典，像这样情况改动就很小，只需在应用中设置IdentityClaimOptions即可。

**Comment by zhenlei520** [comment]
我们计划在0.6.0安排时间重构IdentityModel，使得ICurrentUser可以支持自定义UserModel，Roles类型的问题后面会与对应的开发沟通一下，这里应该是不需要名称
