### ISSUE TITLE
Minimal APIs support auto map for RESTful

### ISSUE THREAD

**Issue by doddgu** [masastack/MASA.Framework#2]
like mvc controller:
```c#
public class TestService: ServiceBase
{
    public TestService()
    {
        MapToRESTful();
    }

    dynamic Get(int Id)
    {
        // todo something
    }
}
```

**Comment by MayueCif** [comment]
lack `RequireAuthorization` method like `MapControllers().RequireAuthorization()`

**Comment by doddgu** [comment]
@zhenlei520 PTAL, maybe it can add to 0.6?

**Comment by zhenlei520** [comment]
> lack `RequireAuthorization` method like `MapControllers().RequireAuthorization()`

like this?

``` C#
App.MapGet("/ping/healthy", () =>
{
    return "success";
}).RequireAuthorization("user");
```

**Comment by zhenlei520** [comment]
> @zhenlei520 PTAL, maybe it can add to 0.6?

Try to support in 0.6.0

**Comment by doddgu** [comment]
#241
