### ISSUE TITLE
项目模板问题

### ISSUE THREAD

**Issue by DonPangPang** [masastack/MASA.Framework#263]
创建项目模板会会有一个项目无法加载
![image](https://user-images.githubusercontent.com/49866401/191911546-aa7e9399-0885-4585-a75c-8ad029fbd8fa.png)

**Comment by zhenlei520** [comment]
模板版本是？

**Comment by DonPangPang** [comment]
> 模板版本是？

刚更新的模板, 显示引用Masa.Blazor的版本为5.x

**Comment by zhenlei520** [comment]
> > 模板版本是？
> 
> 刚更新的模板, 显示引用Masa.Blazor的版本为5.x

麻烦确定下信息是否一致：

模板信息：
Web Project: WASM
Service Project And Mode: Cqrs & Ddd
* [x]  Add Dapr support
* [x]  Use Dapr Actor
* [x]  Add Authorization And Authentication

**Comment by zhenlei520** [comment]
![V8M ~622XGYI4W$QM77T5D7](https://user-images.githubusercontent.com/9740886/191933737-b42fdcf7-ab2e-46fb-b931-210bd1ed08bf.png)

沟通确认 Web Project为WASM时存在问题，生成解决方案后 `***.Bff`类库路径存在问题 @MayueCif

**Comment by MayueCif** [comment]
dotnet new --install Masa.Template::0.5.62 
fix this
