### ISSUE TITLE
IntegrationEvent持久化主键

### ISSUE THREAD

**Issue by qinxh** [masastack/MASA.Framework#35]
1. integrationeventlog中使用无序的GUID作为主键，可能为影响持久化数据库性能，建议抽象一个ID生成接口，框架使用者可以自行定义
2. 对于服务拆分比较简陋的情况下，可能存在多个服务器公用数据库的问题，建立integrationeventlog增加应用ID或名称用于区分应用

**Comment by doddgu** [comment]
1. 这个建议很好，我们其实有考虑过，只是最近比较忙，后面会提供一个专门用于生成ID的BuildingBlocks集成进去，默认会提供Guid + 雪花Id
2. 这个需求很有意思，app-id将来会作为框架在任意位置都可以获取到的参数，动态注入进去会更好一点。但现阶段也可以通过人肉从配置中读取放进去。


这些我会作为增强加到issue中排期来做，如果你有空，也欢迎你提pr

**Comment by zhenlei520** [comment]
本地消息表支持使用构造器设置主键，它将在 `1.0.0-rc.3` 进行支持，本地消息表增加应用id的功能将安排到 `1.0` 之后再添加支持
