### ISSUE TITLE
wasm引用Masa.Contrib.Service.Caller.HttpClient出现RuntimeIdentifier“browser-wasm”问题

### ISSUE THREAD

**Issue by BuiltWing** [masastack/MASA.Framework#405]
只要wasm有引用的项目使用了Masa.Contrib.Service.Caller.HttpClient这个包，会导致wasm项目出现NETSDK1082	Microsoft.AspNetCore.App 没有运行时包可用于指定的 RuntimeIdentifier“browser-wasm”。可能Masa.Contrib.Service.Caller.HttpClient这个包出现有与BlazorWebAssembly不兼容的引用导致，下面提供复现demo，希望能检查一下Masa.Contrib.Service.Caller.HttpClient这个包。
[MasaTest.zip](https://github.com/masastack/MASA.Framework/files/10388062/MasaTest.zip)

**Comment by doddgu** [comment]
@zhenlei520 PTAL

**Comment by zhenlei520** [comment]
可以暂时使用Blazor Server模式, 与Wasm不兼容的问题会在后面的版本解决

**Comment by BuiltWing** [comment]
好的，我自己先用HttpClient实现，等你们新版本出来后再切换过来

**Comment by zhenlei520** [comment]
ok
