### ISSUE TITLE
The 'Masa.BuildingBlocks.Dispatcher.Events.IMiddleware' class name and 'Microsoft.AspNetCore.Http.IMiddleware' name repetition

### ISSUE THREAD

**Issue by MapleWithoutWords** [masastack/MASA.Framework#427]
At first glance, I thought it was Microsoft middleware. In fact, this middleware of MASA is the command middleware of CRQS and other purposes. Could you please make a distinction so as to facilitate understanding of the concept

**Comment by doddgu** [comment]
@zhenlei520 what do you think?

**Comment by MapleWithoutWords** [comment]
Are you think 'IMasaEventMiddleware' this name is ok? or can you give it better name?

**Comment by zhenlei520** [comment]
> Are you think 'IMasaEventMiddleware' this name is ok? or can you give it better name?

You can use IEventMiddleware, if it is convenient for you, can you contribute pr

**Comment by MapleWithoutWords** [comment]
> IEventMiddleware

Ok, Whether subclasses that inherit from it need to change the class name and file name

**Comment by zhenlei520** [comment]
> > IEventMiddleware
> 
> Ok, Whether subclasses that inherit from it need to change the class name and file name. @zhenlei520

Unified modification, but the original writing will not be deleted for the time being, the expired feature will be added, and how to use the new usage will be specified, and it will be deleted when the official version 1.0.0 is released

**Comment by doddgu** [comment]
I think accepting a break change would make things easier

**Comment by MapleWithoutWords** [comment]
ok,let me confirm step.  @zhenlei520 @doddgu 
1.  add new class file,it's name is :IEventMiddleware
2.  modifcation all inhert from IMiddleware subclass,change to inhert IEventMiddleware? or say: all inhert from IMiddleware subclass unchange?

**Comment by MapleWithoutWords** [comment]
> ok,let me confirm step. @zhenlei520 @doddgu
> 
> 1. add new class file,it's name is :IEventMiddleware
> 2. modifcation all inhert from IMiddleware subclass,change to inhert IEventMiddleware? or say: all inhert from IMiddleware subclass unchange?

wherther need change all subclass's name?  example: ValidatorMiddleware=> ValidatorEventMiddleware

**Comment by doddgu** [comment]
> ok,let me confirm step. @zhenlei520 @doddgu
> 
> 1. add new class file,it's name is :IEventMiddleware
> 2. modifcation all inhert from IMiddleware subclass,change to inhert IEventMiddleware? or say: all inhert from IMiddleware subclass unchange?

If you want compatibility to 1.0, you can inherit IMiddleware and IEventMiddleware



> wherther need change all subclass's name? example: ValidatorMiddleware=> ValidatorEventMiddleware

Yes.

**Comment by MapleWithoutWords** [comment]
> > ok,let me confirm step. @zhenlei520 @doddgu
> > 
> > 1. add new class file,it's name is :IEventMiddleware
> > 2. modifcation all inhert from IMiddleware subclass,change to inhert IEventMiddleware? or say: all inhert from IMiddleware subclass unchange?
> 
> If you want compatibility to 1.0, you can inherit IMiddleware and IEventMiddleware
> 
> > wherther need change all subclass's name? example: ValidatorMiddleware=> ValidatorEventMiddleware
> 
> Yes.

i suggest  direct editor 'IMiddleware',put it changed to 'IEventMiddelware'.   Because compatibility to 1.0 version requires edit  a lot  of class file.   also need add 'IEventMiddelware' support to service. it's a lot of work. If it is only modified on the original basis, the workload is less.

**Comment by doddgu** [comment]
I agree.
But, you need to provide a break change upgrade guide.
@zhenlei520 Is there upgrade guide?

**Comment by zhenlei520** [comment]
It is possible, but you need to introduce this modification in the upgrade guide and in-process event documentation to avoid confusion caused by renaming

Document address: https://github.com/masastack/MASA.Docs

@MapleWithoutWords
