### ISSUE TITLE
框架里的缓存配置，是还不支持哨兵模式吗？

### ISSUE THREAD

**Issue by TonyWong2016** [masastack/MASA.Framework#431]
我看到RedisConfigurationOptions类里定义的属性，和[StackExchange.Redis](https://stackexchange.github.io/StackExchange.Redis/Configuration)的链接属性基本是一致的，但是好像缺少了一些，比如ServiceName，或者是Masa.Framework提供了别的方式可以连接到哨兵集群吗？

**Comment by zhenlei520** [comment]
目前暂未支持
