### ISSUE TITLE
MultilevelCache同时设置滑动过期及绝对过期后调用RefreshAsync报错

### ISSUE THREAD

**Issue by qinxh** [masastack/MASA.Framework#450]
错误重现：
Set一个缓存，绝对过期设置3分钟，滑动过期设置1分钟。在2分钟内调用RefreshAsync会正常执行，在2分钟后再调用RefreshAsync就会报错，具体错误如下：
ERR Error running script(call to f_eee8e8411e108ddb82c33faf93d850ef6e75b272): @user_script:2: ERR value is not an integer or out of range

**Comment by zhenlei520** [comment]
按照操作未能成功复现错误，能否麻烦提供一个简单的Demo用于复现错误？

**Comment by qinxh** [comment]
> 按照操作未能成功复现错误，能否麻烦提供一个简单的Demo用于复现错误？

可能是版本问题，我这是0.6.0，后续升级到1.0我再试一下

**Comment by zhenlei520** [comment]
好的 后续如果仍有问题的话  麻烦提供一个简单的demo

**Comment by doddgu** [comment]
暂时先关闭，如果仍有问题可以reopen
