### ISSUE TITLE
IdCardValidator 不支持null值返回true

### ISSUE THREAD

**Issue by xyfy** [masastack/MASA.Framework#479]
@zhenlei520 

没有找到一种可以标记可选的办法，理论上应该是Idcard在null或者空的情况下通过校验，靠notempty/notnull来控制是否可空，但是目前IdCardValidator没有

_Originally posted by @xyfy in https://github.com/masastack/MASA.Auth/pull/730#discussion_r1124093585_

see the [EmailValidator of fluentvalidation](https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation/Validators/EmailValidator.cs)
it will return true when value is null

**Comment by doddgu** [comment]
我认为可以增加 AllowNull，AllowNullOrEmpty 的属性来控制validation内部判断逻辑。理论上来说验证格式就要符合格式要求，明显null和empty不符合格式要求，返回失败是正确的。但如果明确指定可以为null或empty，那一样返回验证成功只是可选项，而不是默认逻辑。

**Comment by xyfy** [comment]
> 我认为可以增加 AllowNull，AllowNullOrEmpty 的属性来控制validation内部判断逻辑。理论上来说验证格式就要符合格式要求，明显null和empty不符合格式要求，返回失败是正确的。但如果明确指定可以为null或empty，那一样返回验证成功只是可选项，而不是默认逻辑。


[fluentvalidation]内置了NotNull  NotEmpty  这两个校验器，就默认情况它的内置校验器都只校验非null值，可能因为null值没有规则校验意义吧，除非[加上这两个之一才会校验非空](https://stackoverflow.com/questions/21441209/fluentvalidation-string-notnull-versus-notempty)。    按照Webapi正常而言，如果一个字段没有值，会被是赋予null，如果要逆转这个规则，[可以通过这个属性](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayformatattribute.convertemptystringtonull?redirectedfrom=MSDN&view=net-7.0#System_ComponentModel_DataAnnotations_DisplayFormatAttribute_ConvertEmptyStringToNull)

**Comment by zhenlei520** [comment]
按照我们的理解，当需要验证身份证号时，它不应该为null或者empty，但考虑与Fluentvalidation的验证规则冲突，会增加额外的学习成本，这里改为：

当value为null时，验证通过，但当value为empty时，它需要进行验证而非视为验证通过，这与Fluentvalidation的规则一致

@doddgu @xyfy

**Comment by doddgu** [comment]
可以，但null就通过其实仍然隐含了一些逻辑。我仍然认为要加属性，但默认值可以按照你说的规则。

**Comment by zhenlei520** [comment]
@xyfy 你那边方便改一下吗？除了IdCardValidator之外，还有PhoneValidator也有同样的问题

**Comment by xyfy** [comment]
行

**Comment by xyfy** [comment]
但是如果这里改了的话，其它已经调用的地方，就得加上notnull来保证校验逻辑的一致性，这个算BreakChange？ @zhenlei520

**Comment by zhenlei520** [comment]
> 但是如果这里改了的话，其它已经调用的地方，就得加上notnull来保证校验逻辑的一致性，这个算BreakChange？ @zhenlei520

是的，需要在发版描述以及1.0.0 文档的升级指南中写清楚
