### ISSUE TITLE
dotnet new new masafx and restore failed

### ISSUE THREAD

**Issue by JaneConan** [masastack/MASA.Framework#486]
## Description

通过cli创建masafx后，提示restore失败

## Environment

.Net SDK Version:
MASA Framework Version: Masa.Template::0.6.862

## Demo

![1678263359394](https://user-images.githubusercontent.com/26090153/223659276-fae52329-cb92-4704-ae39-b8c739a00c9c.png)

**Comment by zhenlei520** [comment]
模版生成的解决方案中有一个无效的类库，它应该是不存在的，你可以在解决方案中移除它

这个问题应该属于MASA.Templates的，如果方便的话麻烦在[MASA.Templates](https://github.com/masastack/MASA.Templates/issues/new)进行提问
