### ISSUE TITLE
直接关闭 VS 或者程序 dapr 边车没有退出

### ISSUE THREAD

**Issue by fixnil** [masastack/MASA.Framework#507]
## Description
![5bbf057b2b22d4b5a8b77caee3e4358](https://user-images.githubusercontent.com/23046289/226154282-a412a052-da78-4ecc-a62d-e26f096b6b27.png)

## Environment

.Net SDK Version: 
```
.NET SDK:
 Version:   8.0.100-preview.1.23115.2
 Commit:    913e4679b3

.NET SDKs installed:
  6.0.310 [C:\Program Files\dotnet\sdk]
  7.0.300-preview.23122.5 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.1.23115.2 [C:\Program Files\dotnet\sdk]
```
MASA Framework Version:
```
<ItemGroup>
  <PackageReference Include="Dapr.AspNetCore" Version="1.10.0" />
  <PackageReference Include="Masa.Contrib.Development.DaprStarter.AspNetCore" Version="1.0.0-preview.19" />
</ItemGroup>
```

## Demo
个人习惯直接使用集成终端操作，会直接停止应用程序，所以可能会容易重现这个问题

![image](https://user-images.githubusercontent.com/23046289/226154002-435db093-28ed-4f32-a263-037a3ce8dc20.png)

**Comment by fixnil** [comment]
@zhenlei520 的回复：
> 是因为边车的退出是需要收到项目停止的信号，但vs直接关闭，收不到这个信号，也做了一些释放监听，不过都不起作用，目前只有通过ctrl+c的当时才可以正常退出

**Comment by zhenlei520** [comment]
Wait for 1.0.0rc to be released and resolved
