### ISSUE TITLE
IUnitOfWork 注入 API 设计不太友好

### ISSUE THREAD

**Issue by okkoye** [masastack/MASA.Framework#537]
## 背景
准备用 MASA.Framework 实现一个有关用户的 CURD 接口服务。

## 问题
定义了 `UserRepository` 继承了 `Repository` 的实现 

![image](https://user-images.githubusercontent.com/48524298/229693586-edb9181e-f347-443b-ad4a-9fbee132c40a.png)

并在 `Program` 注入了该仓储以及 `DbContext` 

![image](https://user-images.githubusercontent.com/48524298/229694406-f385610d-af98-4c06-9515-3677ef423590.png)

当我启动的时候，会抛异常缺少依赖 `IUnitOfWork`。

## 尝试解决

1. 查看官方文档发现可以在配置 `EventBus` 的时候提供 `UseUow` 注入 `IUnitOfWork` 服务。

## 期望

1. 配置仓储或者 `DbContext` 中提供 `UseUow` 注入 `API`，类似与提供一个 `AddRepository` 的接口自动扫描注入 `IxxRepo` 以及实现 并注入 `UseUow`，仅供参考。

**Comment by doddgu** [comment]
@zhenlei520 PTAL

**Comment by zhenlei520** [comment]
十分感谢你的建议

**目前**MasaFramework中提供的**Repository**是并**不是传统意义**上用来**对数据做增删改查**的，它**属于DDD**的概念，因此它不能脱离DDD而单独使用，但考虑到并不是所有的项目都会使用DDD，因此在2.0中我们会**提供**对**数据的抽象**，**在不使用DDD时也可以使用它**，并且我们将为其提供EFCore的实现，并支持后续SqlSugar、FreeSql等ORM的对接，工作单元也是类似，它们将脱离DDD单独存在，而原来DDD中Repository的实现也将更换为新的数据抽象，这样一来，无论项目使用DDD还是不使用，都可以很方便的使用它

**Comment by doddgu** [comment]
在我们的理解中，仓储是一个个独立的烟囱，哪怕可以像DDD那样对聚合根进行夺标操作他仍然是个独立的个体。
而UoW则是协调每个烟囱从独立的个体发展为协作模式。

早期设计中为了快速实现DDD就做的比较耦合，1.0这个版本我们追求的是尽量覆盖功能留下高可扩展性。而2.0将会重构为更合理的架构。

btw：很多小伙伴也问我们可不可以pr，顺便说一下如果你对底层框架设计感兴趣也可以加入到我们当中一起来维护MF，感谢支持。
