### ISSUE TITLE
引用Masa.Contrib.StackSdks.Tsc包，依赖Newtonsoft Json报错

### ISSUE THREAD

**Issue by chobon8** [masastack/MASA.Framework#540]
### Description

![image](https://user-images.githubusercontent.com/52020866/230550608-bf1df975-fc7f-4bd4-a97a-0a4d909a3727.png)
项目中没有依赖Newtonsoft.Json

### .NET version

.NET 6.0

### MASA Framework version

1.0.0-preview.26

**Comment by Qinyouzeng** [comment]
OK,已收到，我们会尽快排查问题，尽快解决问题

**Comment by zhenlei520** [comment]
@chobon8 这个问题已经很久没有消息了。为了保证我们的问题清单保持最新状态，我们将关闭当前 issues，如果问题仍然未解决，可以重新打开它并继续提问
