### ISSUE TITLE
框架为什么要默认禁用实体跟踪，EFCore默认是开始跟踪的

### ISSUE THREAD

**Issue by chobon8** [masastack/MASA.Framework#541]
### Description

用户本来用EFCore都已经养成习惯了，为什么要强迫用户去改变？如果需要关闭跟踪，用户可以自己配置  没必要改变默认配置，这么做有什么好处？

### .NET version

.NET 6.0

**Comment by chobon8** [comment]
在升级1.0.0-preview.26前，我用懒加载正常，升级后报错了
![94a6262f56bf31e591f8b391bb34830](https://user-images.githubusercontent.com/52020866/230571311-47c302d9-9b7f-4748-a8ae-90f81ae7cfb5.png)

**Comment by DonPangPang** [comment]
可以提高一些性能，但是要保持一致性，慎用。

**Comment by chobon8** [comment]
> 可以提高一些性能，但是要保持一致性，慎用。

这个完全可以交给用户自己去选择是否关闭

**Comment by doddgu** [comment]
默认禁用实体跟踪不会改变，文档会增加醒目提示并告知如何手动开启。理论上对写法不会有任何影响，如果影响到了，那可能将来我们支持更换orm你也要调整写法。

@zhenlei520 记得更新文档

**Comment by zhenlei520** [comment]
👌👌
