### ISSUE TITLE
EventBus support Publish a object

### ISSUE THREAD

**Issue by MapleWithoutWords** [masastack/MASA.Framework#591]
In some scenarios, I use IEventBus to publish an event, but the type of the event parameter is object. Currently, MASA Framework must display the specified parameter type.

My event argument is reflection created.As Follows:
![image](https://user-images.githubusercontent.com/38368335/235283785-35cb183f-0af6-455d-be8f-1b438b6b56e4.png)

**Comment by MapleWithoutWords** [comment]
object type's event is inherts Event class

**Comment by doddgu** [comment]
It could be an overloading.

**Comment by zhenlei520** [comment]
> object type's event is inherts Event class

CommandType is determined and can be executed through the generic method of EventBus. This scenario is very rare, and users rarely operate in this way. I think this does not need to be supported. What do you think？@doddgu

**Comment by doddgu** [comment]
If we don't use it, ignore it. Obtaining the type of an object is not difficult for developers.

**Comment by MapleWithoutWords** [comment]
ok
