### ISSUE TITLE
当继承自Event的类为泛型时，会报Getting xxxx relationship chain failed

### ISSUE THREAD

**Issue by xiaomazz** [masastack/MASA.Framework#599]
浮现步骤
【1】定义一个ETO
public record CacheRefreshEto<TKey> : Event 
{
}
【2】publish
EventBus?.PublishAsync(new CacheRefreshEto<Guid>())!

【结果】
Getting CacheRefreshEtoxxxx relationship chain failed

【原因】
  
![495cd524ce57c6e32a9a27b630d200b](https://user-images.githubusercontent.com/52307384/236501172-eee25cc8-e17f-46c1-af41-9c6516d05468.png)
![e10f4da776da1df1c74470fa3667713](https://user-images.githubusercontent.com/52307384/236501190-ee909e57-aca9-4576-adf0-9441d5cf96f4.png)
![6032b9c9ccc222cd231d6f8fb5b365d](https://user-images.githubusercontent.com/52307384/236501213-2e4881b4-7c4c-4e74-9fdf-4cd0aee7d90b.png)

期望，能够支持一下继承自event泛型eto的支持

**Comment by doddgu** [comment]
@zhenlei520 PTAL

**Comment by zhenlei520** [comment]
目前版本不支持泛型事件，这不是一个常见的操作，但我们会在1.0.0之前尽力解决
