### ISSUE TITLE
希望MinimalAPI的ServiceBase可以获取service的Attribute

### ISSUE THREAD

**Issue by raokun** [masastack/MASA.Framework#600]
## 希望MinimalAPI的ServiceBase可以获取Service的Attribute

目前在用MinimalAPI做接口，权限验证只能在方法上加 [Authorize] ，在Service类上加的 AuthorizeAttribute不会被识别。希望能够新增该内容以实现一些通用的配置可以在通过在Service上可以设置Attribute，完成Service中所有接口。

希望service base支持一些基于class的通用操作。

**Comment by doddgu** [comment]
@zhenlei520 PTAL

**Comment by zhenlei520** [comment]
This is a new feature, rc is mainly to fix bugs，It will be supported in 2.0

**Comment by duiapro** [comment]
高级功能请使用api 控制器
