### ISSUE TITLE
Masa.Contrib.StackSdks.Tsc缺少了AddObservable方法

### ISSUE THREAD

**Issue by AugustCai** [masastack/MASA.Framework#606]
### Description

Masa.Contrib.StackSdks.Tsc缺少了AddObservable方法
![1683540605036](https://user-images.githubusercontent.com/21023697/236797637-e6cb3f4d-7b06-4e38-8deb-2df3e6b75b8b.png)

### .NET version

.NET 6

### MASA Framework version

v0.6

**Comment by zhenlei520** [comment]
@MayueCif PTAL

**Comment by MayueCif** [comment]
安装最新预览版
