### ISSUE TITLE
“Masa.Contrib.Service.Caller.DaprClient”包找不到“AddAutoRegistrationCaller”扩展方法

### ISSUE THREAD

**Issue by Tangtang1997** [masastack/MASA.Framework#627]
### Description

根据[文档](https://docs.masastack.com/framework/building-blocks/caller/daprclient#section-69825ff5)，我在本地安装了“Masa.Contrib.Service.Caller.DaprClient”包，但是找不到“AddAutoRegistrationCaller”扩展方法。

文档截图：
![image](https://github.com/masastack/MASA.Framework/assets/46021085/5e40884c-3ef1-4ad8-9fbd-a8d67f0d44a5)
代码截图：
![image](https://github.com/masastack/MASA.Framework/assets/46021085/29e1d221-aad9-42bd-96d0-b8a5b6749688)
![image](https://github.com/masastack/MASA.Framework/assets/46021085/a63a8777-0827-4730-bb27-bc9c6d570897)

### .NET version

6

### MASA Framework version

0.6.0

**Comment by MayueCif** [comment]
使用最新版本，勾选preview

**Comment by GuanghuiJia** [comment]
> 使用最新版本，勾选preview

只有一个0.6.0版本
![image](https://github.com/masastack/MASA.Framework/assets/117328250/731b5561-7c11-4d83-b7f9-e15d788af688)

**Comment by Tangtang1997** [comment]
> 使用最新版本，勾选preview

只有0.6.0一个版本
![image](https://github.com/masastack/MASA.Framework/assets/46021085/e32335a8-7c5e-4811-87b7-c1ac39c7600f)

**Comment by MayueCif** [comment]
![image](https://github.com/masastack/MASA.Framework/assets/6133287/aec8395c-77e4-40e6-b6cc-7c27ceeffcf7)
勾选这里，或者等这周发1.0 直接更新1.0

**Comment by Tangtang1997** [comment]
> ![image](https://user-images.githubusercontent.com/6133287/255464833-aec8395c-77e4-40e6-b6cc-7c27ceeffcf7.png) 勾选这里，或者等这周发1.0 直接更新1.0

找到了，谢谢
