### ISSUE TITLE
masaframework  ef的OR扩展有BUG

### ISSUE THREAD

**Issue by duiapro** [masastack/MASA.Framework#663]
### Description

masaframework  ef的OR扩展有个BUG哈，第一个条件使用or扩展，最终生成的sql会加不上这个筛选条
件。属于必现的BUG
![image](https://github.com/masastack/MASA.Framework/assets/58941749/4bd2f4e2-a6c5-4345-aa59-b721a57121fb)

### MASA Framework version

1.0.0-rc.4.4

**Comment by MayueCif** [comment]
where= order=>true; ，在拼or 条件肯定把后面的省略。即1==1 or 条件情况。
