### ISSUE TITLE
OpenTelemetry - Add Sources

### ISSUE THREAD

**Issue by lefig** [masastack/MASA.Framework#664]
### Description

Firstly, this is a superb piece of work which is well designed and maintained. Thank you all!

I have a query regarding Tracing Prometheus. 

In my code I have:

public static IServiceCollection AddOpenTelemetry(this IServiceCollection services)
        {
            services.AddMasaTracing(options =>
            {
                //api exclude swagger and healthy request
                options.AddAspNetCoreInstrumentation(o =>
                {
                    o.Filter = ctx => ctx.Request.Path != "/metrics";
                });
                options.AddHttpClientInstrumentation();
                **options.AddSource(MessageBroker.TraceActivityName);**
                options.AddOtlpExporter();
                });

            return services;
        }

And I was wondering what the best approach is for adding a list of trace sources. I don't seem to be able to locate any examples and the test appears to be for Logging I think (and not Trace).

namespace Masa.Contrib.StackSdks.Tsc.OpenTelemetry.Tests.Trace;

[TestClass]
public class TraceTests
{
    [TestMethod]
    public void MasaTraceTest()
    {
        var logRecords = new List<LogRecord>();
        bool isConfigureCalled = false;
        using var loggerFactory = LoggerFactory.Create(builder =>
        {
            var resources = ObservableHelper.CreateResourceBuilder();
            var uri = new Uri(ObservableHelper.OTLPURL);

            builder.AddMasaOpenTelemetry(builder =>
            {
                builder.SetResourceBuilder(resources);
                builder.AddOtlpExporter(options =>
                {
                    if (uri != null)
                        options.Endpoint = uri;
                });
                builder.AddInMemoryExporter(logRecords);
                isConfigureCalled = true;
            });
        });

        Assert.IsTrue(isConfigureCalled);
    }
}

**Comment by Qinyouzeng** [comment]
Hi，you can reference [OpenTelemetry](https://opentelemetry.io/docs/specs/otel/resource) doc

```C#
public static IServiceCollection AddOpenTelemetry(this IServiceCollection services)
    {
        return services.AddMasaTracing(options =>
        {
            var resources = ResourceBuilder.CreateDefault()
            //set resources
            .AddAttributes(new List<KeyValuePair<string, object>> {
                new KeyValuePair<string, object>("key1","value1"),
                new KeyValuePair<string, object>("key2","value2"),
            }); 
            // or native in OpenTelemetry: services.AddOpenTelemetry().ConfigureResource(resources=>{})


            //api exclude swagger and healthy request
            options.AddAspNetCoreInstrumentation(o =>
            {
                o.Filter = ctx => ctx.Request.Path != "/metrics";
            });
            options.AddHttpClientInstrumentation();
            options.AddSource(MessageBroker.TraceActivityName);
            options.AddOtlpExporter();
        });
    }
```

**Comment by lefig** [comment]
Perfect. 

Thank you.
