### ISSUE TITLE
IEventBus是否可以支持批量发布事件呢

### ISSUE THREAD

**Issue by magiboys** [masastack/MASA.Framework#695]
现在发布集成事件，如果数据量大，逐个发布事件到dapr是有性能损耗的。
dapr支持批量发布事件，希望加强IEventBus的批量发布事件能力

**Comment by duiapro** [comment]
请提供业务场景

**Comment by magiboys** [comment]
比如消息推送，一个消息生成，我会给订阅这个消息的每个用户生成一条消息推送事件，目前集成事件依赖Dapr，单个循环推送，有性能损耗，目前是通过DaprClient直接调用BulkPublishEventAsync批量推送解决

**Comment by magiboys** [comment]
> 比如消息推送，一个消息生成，我会给订阅这个消息的每个用户生成一条消息推送事件，目前集成事件依赖Dapr，单个循环推送，有性能损耗，目前是通过DaprClient直接调用BulkPublishEventAsync批量推送解决

比如消息推送，一个消息生成，我会给订阅这个消息的每个用户生成一条消息推送事件，目前集成事件依赖Dapr，单个循环推送，有性能损耗，目前是通过DaprClient直接调用BulkPublishEventAsync批量推送解决
