### ISSUE TITLE
UserFriendlyException 构造函数功能缺陷

### ISSUE THREAD

**Issue by magiboys** [masastack/MASA.Framework#697]
### Description

UserFriendlyException类，如果我要传message,  logLevel参数构造类，发现没有对应的构造函数，是否提供一个带所有参数的构造函数以便开发者灵活调用

**Comment by duiapro** [comment]
你说的这个目前是支持的。    
public UserFriendlyException(
        string errorCode,
        LogLevel? logLevel,
        params object[] parameters)
        : base(errorCode, logLevel, parameters)
    {
    }
