### ISSUE TITLE
使用.NET8的KeyService无法运行项目

### ISSUE THREAD

**Issue by 239573049** [masastack/MASA.Framework#703]
### Description

在注册了KeyService服务以后AddMapster的时候异常，在debug的时候
![image](https://github.com/masastack/MASA.Framework/assets/61819790/e7ecfab4-1941-44ea-b6d5-2736d47542cb)
这个判断异常

**Comment by duiapro** [comment]
你好，无法复现这个异常问题，请问异常信息是提示信息能捕捉到吗，发我一下我做个参考
