### ISSUE TITLE
实体继承FullAggregateRoot聚合根后，修改数据创建时间会一并被修改

### ISSUE THREAD

**Issue by SpiderMan95** [masastack/MASA.Framework#705]
### Description

创建实体继承了FullAggregateRoot，修改数据时创建时间也一并被修改了
![image](https://github.com/masastack/MASA.Framework/assets/29696982/a70e7f30-87e0-4581-837a-d41a573d32fb)

### .NET version

8.0

**Comment by duiapro** [comment]
并不会哦，这里只是实例化赋值
