### ISSUE TITLE
集成事件默认Topic,可能引起命名冲突

### ISSUE THREAD

**Issue by magiboys** [masastack/MASA.Framework#716]
### Description

![1714007196329](https://github.com/masastack/MASA.Framework/assets/124755355/62496da1-ae7d-4ec5-8c34-70d6e2fdf736)
目前默认Topic是取当前类型的Name,这在分布式系统中可能有命名冲突，是否应更改为FullName

**Comment by duiapro** [comment]
改成FullName会增加消费端TopicName定义难度和舒适性，命名冲突为少数情况利大于弊。如命名冲突建议手动重写Event类Topic属性
