### ISSUE TITLE
为服务调用错误指定专门的异常类

### ISSUE THREAD

**Issue by magiboys** [masastack/MASA.Framework#720]
### Description

目前当服务调用发生异常，如403，400，500，错误时，都是统一抛出MasaException异常（只会记录返回的内容），是否定制一个异常，如Refit库的ApiException异常一样，保存本次请求的StatusCode，RequestUri，RequestMessage，HttpMethod,AppId等等信息
![image](https://github.com/masastack/MASA.Framework/assets/124755355/6a395b58-5d86-4443-af8a-7f687b4c9393)

**Comment by masastack-opensource** [comment]
并没有这样的计划，MASA TSC能够满足要求，如果你有意愿贡献，非常欢迎！
