### ISSUE TITLE
执行Update时报错：The database operation was expected to affect 1 row(s), but actually affected 0 row(s); 

### ISSUE THREAD

**Issue by ihuangxing** [masastack/MASA.Framework#730]
### Description

在Command中执行实体更新时报错：The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded.

### Reproduction Steps

#主模型
Model Order{
   string Name {get;set;}
   List<OrderItem> Items {get;set;}
}
#子模型
Model OrderItem{
   Order Order{get;set;}
  Guid OrderId{get;set;}

   string Name{get;set;}
   double Price{get;set;}
}

// UpdateOrderCommond代码

//1、查询已存在的实体，并Include 子模型集合
var list = await _orderRepository.GetListAsync(x=> x.Id == xxx);
var order = list.FirstOrDefault();

// 2、对子集合添加一条数据
order.Items.Add(new{
 Name: 'xxx',
Price: 111
});

// 3、执行更新主模型
await _orderRepository.UpdateAsync(order);

// miniapi调用
var cmd = new UpdateOrderCommand(id);

### Expected behavior

正常更新主模型并新增一条OrderItem明细

### Actual behavior

The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded.

所有订单明细全部执行Update，而非Insert。

### Known Workarounds

EFCore本身是支持这种场景的，但在MASA Framework中执行会出错。

### .NET version

7

### MASA Framework version

1.0.0

### Other information

请检查Entity.State的状态是否正确

**Comment by Qinyouzeng** [comment]
从表进行添加时设置了主键，而从表主键又是自增类型导致
